name: 'Checkout Fetch All'
description: 'Uses actions/checkout@v3 to fetch all history, branches, and tags which require Personal Access Token.'

branding:
  icon: 'git-branch'
  color: 'purple'

inputs:
  token:
    description: 'Personal Access Token.'
    type: string
    required: true

runs:
  using: "composite"
  steps:
    uses: actions/checkout@v3
    with:
      fetch-depth: 0
      token: ${{ inputs.token }}
